# $FreeBSD$

.include <bsd.own.mk>

LIB=		helloworld
SHLIB_MAJOR=	0

LIBDIR=		${TESTSBASE}/libexec/rtld-elf
SHLIBDIR=	${TESTSBASE}/libexec/rtld-elf

SRCS=		helloworld.c

LIBADD=		m

.include <bsd.lib.mk>
